openapi: 3.0.0
info:
  title: School Management API
  version: 1.0.0
  description: APIs for adding and listing schools by proximity
paths:
  /api/addSchool:
    post:
      summary: Add a new school
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
      responses:
        "201":
          description: School added
        "400":
          description: Invalid input
        "500":
          description: Server error
  /api/listSchools:
    get:
      summary: List schools sorted by proximity
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
        - name: lon
          in: query
          required: true
          schema:
            type: number
      responses:
        "200":
          description: Sorted list of schools
        "400":
          description: Invalid coordinates
        "500":
          description: Server error
